services:
  db:
    image: postgres
    container_name: eletro-reparos-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - default
    
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: eletro-reparos-api
    command: npm run start:debug
    ports:
      - "3000:3000"
    volumes:
        - .:/app
        - /app/node_modules
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - default


networks:
  default:
      name: eletro-reparos-network

volumes:
  db-data: